### ISSUE TITLE
Ability to use bullfrog as part of standalone linux host

### ISSUE THREAD

**Issue by rams3sh** [bullfrogsec/bullfrog#63]
In my current project, I'm aiming to implement a security measure on a host instance. This involves restricting outbound network access to a predefined list of trusted domains.

I came across this project recently, which I understood offers similar functionality within the context of GitHub workflows. 
I was interested in exploring this project for my use case. I downloaded the agent and used the below command and got the below error :- 
```
bf@lab:~/Downloads/agent $ ls
agent  allowed_domains.txt
bf@lab:~/Downloads/agent $ sudo ./agent -egress-policy block
Blocking mode enabled
DNS queries to unallowed domains will be blocked
loading allowed ips
No allowed_ips.txt file found, using defaults only
loading allowed domains
Network interface: wlp9s0
cmd: resolvectl status wlp9s0 | grep 'DNS Servers' | awk '{print $3}'
DNS Server: 8.8.8.8
2024/07/09 17:21:50 Error adding to nftables: Error adding 169.254.169.254 to nftables: exit status 1
```
Any references / guide will really be helpful to simulate github action like environment in local host. 

Will  there be any plans for the host based solution ?

**Comment by fallard84** [comment]
Hey @rams3sh,
thanks for your interest in this project. We plan on releasing a version of the agent that can be deployed on a self-hosted Github Actions runner. But if I understand correctly, you are trying to deploy this outside of Github Actions.

If that's the case, here's some info that could be helpful for you. At this moment, the agent isn't really built to be used standalone, and it requires the Javascript action component to setup a few things on the runner before the agent can be fully functionally. The agent is using nftables to set IP filtering on the host, and is intercepting DNS requests using [libnetfilter_queue](https://www.netfilter.org/projects/libnetfilter_queue/). So you need to install those 2 packages:
```bash
apt-get install libnetfilter-queue-dev nftables
```
The agent is also expecting predefined rules in nftables, here is the rules file that gets loaded at initialization in blocking mode and also only allowing DNS requests for trusted domains: https://github.com/bullfrogsec/bullfrog/blob/main/agent/queue_block_with_dns.nft

Note that by adding these rules and without the agent properly functioning, you will block all egress connections. If you need to temporarily remove the restrictions, you can flush nftables:
```bash
sudo nft flush ruleset
```

Hope that helps!

**Comment by rams3sh** [comment]
Hey @fallard84 

I understand this question was beyond the scope of bullfrog. And I really appreciate you to have responded to it despite that.
This really helps. 

Hence, closing the ticket.
